version: 1
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
              TaskDefinition: "arn:aws:codebuild:ap-south-1:821413715091:project/DEMO"
              LoadBalancerInfo:
                      ContainerName: "artoon"
                      ContainerPort: 3001




