name: Build & Deploy
on:
  push:
    branches:
      main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Website
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          Script: |
            cd /var/www/html/demo/
            git pull origin main
